language: go
sudo: false
env:
  global:
    secure: PEHwJg5ncCwVZcHRkFgTXYMIQHjuU6u6u/Z8ZoAOU8qvHsNanMQhKQaT4kyBfE4Ls/sNXPO53Li/ROWAR75fx4hqrRgQgT95JWCB40t7ftbQoUtEUOa/VU+bQLUC/vcvVDirpBG5zBQNrvKdIH7vMWq6LhXE0hthyiw8+OmVzHU=
notifications:
  email:
    recipients: jesse@ccs.neu.edu
    on_success: change
    on_failure: always
go:
- tip
before_script:
- go get github.com/smartystreets/goconvey/convey
before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
script:
- $HOME/gopath/bin/goveralls -package ./... -repotoken $COVERALLS_TOKEN
